version: 2
project_name: quickdup

builds:
  - id: quickdup
    dir: .
    main: ./cmd/quickdup
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: asynkron
    name: QuickDup
  draft: false
  prerelease: false
